export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_EDIT_ITEM = 'CART_EDIT_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';

export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
